CREATE DATABASE IF NOT EXISTS blog_app;

CREATE TABLE IF NOT EXISTS blog_app.users
(
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);